name: cenerg
description: Application de gestion d'énergie pour iOS et Android
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  permission_handler: ^11.3.0
  device_info_plus: ^9.1.2
  package_info_plus: ^5.0.1
  platform_device_id: ^1.0.1
  cupertino_icons: ^1.0.6
  postgres: ^2.6.3
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#0078FF"
  adaptive_icon_foreground: "assets/app_icon.png"
